# Generated by Django 2.2.10 on 2020-02-23 18:26

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, null=True)),
                ('user_password', models.CharField(max_length=200, null=True)),
                ('user_contact', models.CharField(max_length=200, null=True)),
                ('user_email', models.EmailField(max_length=254, null=True)),
                ('user_country', models.CharField(max_length=200, null=True)),
                ('user_country_name', models.CharField(max_length=200, null=True)),
                ('item_totals', models.CharField(max_length=200, null=True)),
                ('item_quantities', models.CharField(max_length=200, null=True)),
                ('item_indexes', models.CharField(max_length=200, null=True)),
                ('item_descriptions', models.CharField(max_length=200, null=True)),
                ('item_delivery', models.DateTimeField(default=main.models.User.time_under_timezone, verbose_name='Date of Delivery')),
                ('user_ip', models.CharField(default=0, max_length=200)),
            ],
        ),
    ]
