# Generated by Django 2.2.10 on 2020-02-23 18:42

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_totals', models.CharField(blank=True, max_length=200, null=True)),
                ('item_quantities', models.CharField(blank=True, max_length=200, null=True)),
                ('item_indexes', models.CharField(blank=True, max_length=200, null=True)),
                ('item_descriptions', models.CharField(blank=True, max_length=200, null=True)),
                ('item_delivery', models.DateTimeField(default=main.models.Customer.time_under_timezone, verbose_name='Date of Delivery')),
                ('purchase_date', models.DateTimeField(default=main.models.Customer.time_under_timezone, verbose_name='Date of Purchase')),
                ('user_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
    ]
